---
- hosts: localhost
  connection: local
  become: yes
  become_user: root
  become_method: su
  vars_files:
    - vhost.yml
  tasks:
    - name: yum install httpd
      yum: name=httpd state=present

    - name: httpd の起動と自動起動設定
      service: name=httpd state=running enabled=yes

    - name: firewallにhttpdを追加
      firewalld:
        service=http
        permanent=true
        state=enabled
        immediate=true

    - name: DocumentRootの作成
      file: path={{ document_root }} state=directory owner={{ user_name }} group={{ user_name }} mode=0755

    #- name: UserDirを使う場合はユーザーディレクトリのパーミッションを変更する
    #  command: chmod 755 /home/{{ user_name }}
    #  when: user_nameが設定されている場合のみ

    - name: logディレクトリの作成
      file: path=/var/log/httpd/{{ log_dir }} state=directory owner=root group=root mode=0755

    - name: httpd.confをvirtualhost対応に
      lineinfile:
        dest=/etc/httpd/conf/httpd.conf
        state=present
        line={{ item }}
      with_items:
        - "IncludeOptional conf.d/vhost/*.conf"
        - "NameVirtualHost *:80"

    - name: vhostディレクトリの作成
      file: path=/etc/httpd/conf.d/vhost state=directory

    - name: virtualhostファイルを作成
      template: src=template-vhost.j2 dest=/etc/httpd/conf.d/vhost/{{ inventory_hostname }}.conf
      notify: restart httpd


  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
